// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKdp_EP9PHroEsfmuIgwSNJk8JKPv-pJA',
    appId: '1:139201515187:web:ad49f17c0233ca83972ac6',
    messagingSenderId: '139201515187',
    projectId: 'noteapp-f2c19',
    authDomain: 'noteapp-f2c19.firebaseapp.com',
    storageBucket: 'noteapp-f2c19.appspot.com',
    measurementId: 'G-HW4P1V4N9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJDDxkMnuVwEhV1LgIG2iBPPmWvOMX1es',
    appId: '1:139201515187:android:d13ddc2100fa1bc1972ac6',
    messagingSenderId: '139201515187',
    projectId: 'noteapp-f2c19',
    storageBucket: 'noteapp-f2c19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFBj9Kd-psCgucBuTw9Sv1okmsbX9ZdcM',
    appId: '1:139201515187:ios:d87731d9c78b84cb972ac6',
    messagingSenderId: '139201515187',
    projectId: 'noteapp-f2c19',
    storageBucket: 'noteapp-f2c19.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFBj9Kd-psCgucBuTw9Sv1okmsbX9ZdcM',
    appId: '1:139201515187:ios:d453a710d451b7ea972ac6',
    messagingSenderId: '139201515187',
    projectId: 'noteapp-f2c19',
    storageBucket: 'noteapp-f2c19.appspot.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
